createOrReplace

	table 'Key Measures'

		/// m1 = 1
		measure 'm1' = 1	

		partition 'Key Measures' = m
			mode: import
			source = 
					let
						Source = Table.FromRows(
							Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)),
							let
								_t = ((type nullable text) meta [Serialized.Text = true])
							in
								type table [Column1 = _t]
						),
						#"Changed Type" = Table.TransformColumnTypes(Source, {{"Column1", type text}}),
						#"Removed Columns" = Table.RemoveColumns(#"Changed Type", {"Column1"})
					in
						#"Removed Columns"

		annotation PBI_ResultType = Table
